name: sshfs

services:
  test:
    build:
      dockerfile_inline: |
        FROM alpine

        RUN apk add sshfs
    devices:
      - /dev/fuse
    command: sleep 10000
    stop_signal: SIGKILL
    volumes:
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
