name: nc

services:
  php:
    build: php
    restart: unless-stopped
    environment:
      TZ: Asia/Yekaterinburg
      PHP_INI_SCAN_DIR: /etc/php/5.6/fpm/conf.d:/repo/php5.6/etc/php/5.6/fpm/conf.d
    volumes:
      - repo:/repo:ro
      - type: volume
        source: repo
        target: /etc/php/5.6/fpm/pool.d
        read_only: true
        volume:
          subpath: php5.6/etc/php/5.6/fpm/pool.d
    depends_on:
      - repo

  www:
    image: nginx:latest
    restart: unless-stopped
    environment:
      TZ: Asia/Yekaterinburg
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - repo:/repo:ro
      - type: volume
        source: repo
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          subpath: php5.6/etc/nginx/conf.d
    depends_on:
      - php

  repo:
    build: repo
    restart: unless-stopped
    environment:
      GIT_REPO: https://github.com/ukoloff/sigur.log.git
      GIT_BRANCH: php5.6
    volumes:
      - repo:/repo
      # - devtools:/root
    # Only for local docker:
    # secrets:
    #   - oops
    # configs:
    #   - oops

volumes:
  repo:
  devtools:

secrets:
  oops:
    file: oops/oops.txt

configs:
  oops:
    file: oops/oops.ini
