name: nc

services:
  php:
    build: php
    volumes:
      - src:/code

  www:
    image: nginx:latest
    ports:
      - 0.0.0.0:8080:80
    depends_on:
      - php
    volumes:
      - src:/code

  repo:
    build: repo
    volumes:
      - repo:/repo

volumes:
  repo:
  src:
  vscode:
