name: nc

services:
  php:
    build: php
    volumes:
      - repo:/repo

  www:
    image: nginx:latest
    ports:
      - 0.0.0.0:8080:80
    depends_on:
      - php
    volumes:
      - repo:/repo

  repo:
    build: repo
    environment:
      GIT_REPO: https://github.com/ukoloff/sigur.log.git
      GIT_BRANCH: php5.6
    volumes:
      - repo:/repo
      # - devtools:/root

volumes:
  repo:
  devtools:
