name: nc

services:
  php:
    build: php
    volumes:
      - repo:/repo:ro
      - type: volume
        source: repo
        target: /etc/php/5.6/fpm/pool.d
        read_only: true
        volume:
          subpath: php5.6/etc/php/5.6/fpm/pool.d
    depends_on:
      - repo

  www:
    image: nginx:latest
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - repo:/repo:ro
      - type: volume
        source: repo
        target: /etc/nginx/conf.d
        read_only: true
        volume:
          subpath: php5.6/etc/nginx/conf.d
    depends_on:
      - php

  repo:
    build: repo
    environment:
      GIT_REPO: https://github.com/ukoloff/sigur.log.git
      GIT_BRANCH: php5.6
    volumes:
      - repo:/repo
      # - devtools:/root

volumes:
  repo:
  devtools:
