name: nc

services:
  php:
    build: php
    volumes:
      - src:/code

  www:
    image: nginx:latest
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - src:/code

  cp:
    build: cp
    volumes:
      - src:/code

volumes:
  src: